insert into users(id, version, email, password, enabled) values (1, 1, 'michal@gmail.com', '{noop}password', 1);
insert into users(id, version, email, password, enabled) values (2, 1, 'jan@gmail.com', '{noop}password', 1);

insert into movie(id, version, name) values (1, 1, 'The Shawshank Redemption');
insert into movie(id, version, name) values (2, 1, 'The Godfather');
insert into movie(id, version, name) values (3, 1, 'The Dark Knight');
insert into movie(id, version, name) values (4, 1, 'Pulp Fiction');
insert into movie(id, version, name) values (5, 1, 'Forrest Gump');
insert into movie(id, version, name) values (6, 1, 'Inception');
insert into movie(id, version, name) values (7, 1, 'Fight Club');
insert into movie(id, version, name) values (8, 1, 'The Matrix');
insert into movie(id, version, name) values (9, 1, 'Goodfellas');
insert into movie(id, version, name) values (10, 1, 'The Lord of the Rings: The Fellowship of the Ring');
insert into movie(id, version, name) values (11, 1, 'The Lord of the Rings: The Two Towers');
insert into movie(id, version, name) values (12, 1, 'The Lord of the Rings: The Return of the King');
insert into movie(id, version, name) values (13, 1, 'Gladiator');
insert into movie(id, version, name) values (14, 1, 'Titanic');
insert into movie(id, version, name) values (15, 1, 'The Silence of the Lambs');
insert into movie(id, version, name) values (16, 1, 'Schindler''s List');
insert into movie(id, version, name) values (17, 1, 'Saving Private Ryan');
insert into movie(id, version, name) values (18, 1, 'Interstellar');
insert into movie(id, version, name) values (19, 1, 'Whiplash');
insert into movie(id, version, name) values (20, 1, 'Se7en');
insert into movie(id, version, name) values (21, 1, 'The Prestige');
insert into movie(id, version, name) values (22, 1, 'Django Unchained');
insert into movie(id, version, name) values (23, 1, 'The Departed');
insert into movie(id, version, name) values (24, 1, 'The Green Mile');
insert into movie(id, version, name) values (25, 1, 'Braveheart');
insert into movie(id, version, name) values (26, 1, 'The Wolf of Wall Street');
insert into movie(id, version, name) values (27, 1, 'The Social Network');
insert into movie(id, version, name) values (28, 1, 'Joker');
insert into movie(id, version, name) values (29, 1, '12 Angry Men');
insert into movie(id, version, name) values (30, 1, 'The Truman Show');
insert into movie(id, version, name) values (31, 1, 'American Beauty');
insert into movie(id, version, name) values (32, 1, 'The Pianist');
insert into movie(id, version, name) values (33, 1, 'No Country for Old Men');
insert into movie(id, version, name) values (34, 1, 'The Big Lebowski');
insert into movie(id, version, name) values (35, 1, 'Her');
insert into movie(id, version, name) values (36, 1, 'The Grand Budapest Hotel');
insert into movie(id, version, name) values (37, 1, 'La La Land');
insert into movie(id, version, name) values (38, 1, 'Parasite');
insert into movie(id, version, name) values (39, 1, '1917');
insert into movie(id, version, name) values (40, 1, 'The Revenant');
insert into movie(id, version, name) values (41, 1, 'Blade Runner 2049');
insert into movie(id, version, name) values (42, 1, 'Mad Max: Fury Road');
insert into movie(id, version, name) values (43, 1, 'Logan');
insert into movie(id, version, name) values (44, 1, 'Spider-Man: Into the Spider-Verse');
insert into movie(id, version, name) values (45, 1, 'Avengers: Endgame');
insert into movie(id, version, name) values (46, 1, 'Iron Man');
insert into movie(id, version, name) values (47, 1, 'Captain America: The Winter Soldier');
insert into movie(id, version, name) values (48, 1, 'Guardians of the Galaxy');
insert into movie(id, version, name) values (49, 1, 'Doctor Strange');
insert into movie(id, version, name) values (50, 1, 'Black Panther');
insert into movie(id, version, name) values (51, 1, 'Deadpool');
insert into movie(id, version, name) values (52, 1, 'X-Men: Days of Future Past');
insert into movie(id, version, name) values (53, 1, 'The Incredibles');
insert into movie(id, version, name) values (54, 1, 'Toy Story');
insert into movie(id, version, name) values (55, 1, 'Finding Nemo');
insert into movie(id, version, name) values (56, 1, 'Up');
insert into movie(id, version, name) values (57, 1, 'Wall-E');
insert into movie(id, version, name) values (58, 1, 'Ratatouille');
insert into movie(id, version, name) values (59, 1, 'Inside Out');
insert into movie(id, version, name) values (60, 1, 'Coco');
insert into movie(id, version, name) values (61, 1, 'Monsters, Inc.');
insert into movie(id, version, name) values (62, 1, 'The Lion King');
insert into movie(id, version, name) values (63, 1, 'Beauty and the Beast');
insert into movie(id, version, name) values (64, 1, 'Aladdin');
insert into movie(id, version, name) values (65, 1, 'Frozen');
insert into movie(id, version, name) values (66, 1, 'Moana');
insert into movie(id, version, name) values (67, 1, 'Zootopia');
insert into movie(id, version, name) values (68, 1, 'Shrek');
insert into movie(id, version, name) values (69, 1, 'How to Train Your Dragon');
insert into movie(id, version, name) values (70, 1, 'Kung Fu Panda');
insert into movie(id, version, name) values (71, 1, 'Despicable Me');
insert into movie(id, version, name) values (72, 1, 'The Secret Life of Pets');
insert into movie(id, version, name) values (73, 1, 'Sing');
insert into movie(id, version, name) values (74, 1, 'The Lego Movie');
insert into movie(id, version, name) values (75, 1, 'Tangled');
insert into movie(id, version, name) values (76, 1, 'Wreck-It Ralph');
insert into movie(id, version, name) values (77, 1, 'Big Hero 6');
insert into movie(id, version, name) values (78, 1, 'Rango');
insert into movie(id, version, name) values (79, 1, 'The Peanuts Movie');
insert into movie(id, version, name) values (80, 1, 'The Croods');
insert into movie(id, version, name) values (81, 1, 'Ice Age');
insert into movie(id, version, name) values (82, 1, 'Rio');
insert into movie(id, version, name) values (83, 1, 'Hotel Transylvania');
insert into movie(id, version, name) values (84, 1, 'Cloudy with a Chance of Meatballs');
insert into movie(id, version, name) values (85, 1, 'Happy Feet');
insert into movie(id, version, name) values (86, 1, 'The Lorax');
insert into movie(id, version, name) values (87, 1, 'The Angry Birds Movie');
insert into movie(id, version, name) values (88, 1, 'Minions');
insert into movie(id, version, name) values (89, 1, 'The Boss Baby');
insert into movie(id, version, name) values (90, 1, 'Puss in Boots');
insert into movie(id, version, name) values (91, 1, 'Megamind');
insert into movie(id, version, name) values (92, 1, 'Madagascar');
insert into movie(id, version, name) values (93, 1, 'Cars');
insert into movie(id, version, name) values (94, 1, 'Bolt');
insert into movie(id, version, name) values (95, 1, 'Brave');
insert into movie(id, version, name) values (96, 1, 'Monsters University');
insert into movie(id, version, name) values (97, 1, 'A Bug''s Life');
insert into movie(id, version, name) values (98, 1, 'Luca');
insert into movie(id, version, name) values (99, 1, 'Turning Red');
insert into movie(id, version, name) values (100, 1, 'Elemental');

insert into authorities(email, authority) values ('michal@gmail.com', 'user');
insert into authorities(email, authority) values ('michal@gmail.com', 'admin');
insert into authorities(email, authority) values ('jan@gmail.com', 'user');
