name: movie-rating-db-and-monitoring

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:14.18
    container_name: postgres
    environment:
      POSTGRES_USER: movie_rating_user
      POSTGRES_PASSWORD: movie_rating_user
      POSTGRES_DB: movie_rating
    networks:
      - movie-rating-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./posgresql/init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  # Prometheus Service
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - movie-rating-monitoring
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:3.5.3
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - movie-rating-monitoring
    command: -config.file=/etc/loki/local-config.yaml

  # Grafana Service
  grafana:
    image: grafana/grafana:12.2.0-16636675413
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    networks:
      - movie-rating-monitoring
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  postgres-data:
  prometheus-data:
  grafana-data:

networks:
  movie-rating-db:
  movie-rating-monitoring: