server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  name: movie-rating-service
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_rating
    username: movie_rating_user
    password: movie_rating_user
    hikari:
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public

logging:
  level:
    com.github.movierating: INFO